// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// payChannelApplyDao is the data access object for the table hg_pay_channel_apply.
// You can define custom methods on it to extend its functionality as needed.
type payChannelApplyDao struct {
	*internal.PayChannelApplyDao
}

var (
	// PayChannelApply is a globally accessible object for table hg_pay_channel_apply operations.
	PayChannelApply = payChannelApplyDao{internal.NewPayChannelApplyDao()}
)

// Add your custom methods and functionality below.
