// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tAttachmentDao is the data access object for the table t_attachment.
// You can define custom methods on it to extend its functionality as needed.
type tAttachmentDao struct {
	*internal.TAttachmentDao
}

var (
	// TAttachment is a globally accessible object for table t_attachment operations.
	TAttachment = tAttachmentDao{internal.NewTAttachmentDao()}
)

// Add your custom methods and functionality below.
