// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tDictDataDao is the data access object for the table t_dict_data.
// You can define custom methods on it to extend its functionality as needed.
type tDictDataDao struct {
	*internal.TDictDataDao
}

var (
	// TDictData is a globally accessible object for table t_dict_data operations.
	TDictData = tDictDataDao{internal.NewTDictDataDao()}
)

// Add your custom methods and functionality below.
