// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tDictTypeDao is the data access object for the table t_dict_type.
// You can define custom methods on it to extend its functionality as needed.
type tDictTypeDao struct {
	*internal.TDictTypeDao
}

var (
	// TDictType is a globally accessible object for table t_dict_type operations.
	TDictType = tDictTypeDao{internal.NewTDictTypeDao()}
)

// Add your custom methods and functionality below.
