// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"github.com/yclw/mspay/internal/consts"
	"github.com/yclw/mspay/internal/dao/internal"
	"github.com/yclw/mspay/internal/model/entity"
)

// tLogLoginDao is the data access object for the table t_log_login.
// You can define custom methods on it to extend its functionality as needed.
type tLogLoginDao struct {
	*internal.TLogLoginDao
}

var (
	// TLogLogin is a globally accessible object for table t_log_login operations.
	TLogLogin = tLogLoginDao{internal.NewTLogLoginDao()}
)

// Add your custom methods and functionality below.

// GetLoginStat 获取用户登录信息
func (d *tLogLoginDao) GetLoginStat(ctx context.Context, memberId int64) (res *entity.TLogLogin, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).Fields(cols.LoginAt, cols.LoginIp).Where(cols.MemberId, memberId).Where(cols.Status, consts.StatusEnabled).OrderDesc(cols.Id).Scan(&res)
	if err != nil || res == nil {
		return
	}
	return
}

// GetLoginCount 获取用户登录计次
func (d *tLogLoginDao) GetLoginCount(ctx context.Context, memberId int64) (res int, err error) {
	cols := d.Columns()
	res, err = d.Ctx(ctx).Where(cols.MemberId, memberId).Where(cols.Status, consts.StatusEnabled).Count()
	return
}
