// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/yclw/mspay/internal/dao/internal"
	"github.com/yclw/mspay/internal/model/entity"
)

// tMemberInfoDao is the data access object for the table t_member_info.
// You can define custom methods on it to extend its functionality as needed.
type tMemberInfoDao struct {
	*internal.TMemberInfoDao
}

var (
	// TMemberInfo is a globally accessible object for table t_member_info operations.
	TMemberInfo = tMemberInfoDao{internal.NewTMemberInfoDao()}
)

// Add your custom methods and functionality below.

// GetMemberByUsername 根据用户名获取用户信息
func (d *tMemberInfoDao) GetMemberByUsername(ctx context.Context, username string) (member *entity.TMemberInfo, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).Where(cols.Username, username).Scan(&member)
	return
}

// GetMemberById 根据用户ID获取用户信息
func (d *tMemberInfoDao) GetMemberById(ctx context.Context, id int64) (member *entity.TMemberInfo, err error) {
	cols := d.Columns()
	err = d.Ctx(ctx).Where(cols.Id, id).Scan(&member)
	return
}

// GetMemberByRoleIds 根据角色ID获取用户信息
func (d *tMemberInfoDao) GetMemberByRoleIds(ctx context.Context, roleIds []int64) (mod *gdb.Model, err error) {
	cols := d.Columns()
	mod = d.Ctx(ctx).WhereIn(cols.RoleId, roleIds)
	return
}

// GetSubMemberCount 获取下级用户数量
func (d *tMemberInfoDao) GetSubMemberCount(ctx context.Context, id int64) (count int, err error) {
	cols := d.Columns()
	count, err = d.Ctx(ctx).Where(cols.Pid, id).Count()
	return
}
