// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tMemberRoleDao is the data access object for the table t_member_role.
// You can define custom methods on it to extend its functionality as needed.
type tMemberRoleDao struct {
	*internal.TMemberRoleDao
}

var (
	// TMemberRole is a globally accessible object for table t_member_role operations.
	TMemberRole = tMemberRoleDao{internal.NewTMemberRoleDao()}
)

// Add your custom methods and functionality below.
