// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tMenuInfoDao is the data access object for the table t_menu_info.
// You can define custom methods on it to extend its functionality as needed.
type tMenuInfoDao struct {
	*internal.TMenuInfoDao
}

var (
	// TMenuInfo is a globally accessible object for table t_menu_info operations.
	TMenuInfo = tMenuInfoDao{internal.NewTMenuInfoDao()}
)

// Add your custom methods and functionality below.
