// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tNoticeReadDao is the data access object for the table t_notice_read.
// You can define custom methods on it to extend its functionality as needed.
type tNoticeReadDao struct {
	*internal.TNoticeReadDao
}

var (
	// TNoticeRead is a globally accessible object for table t_notice_read operations.
	TNoticeRead = tNoticeReadDao{internal.NewTNoticeReadDao()}
)

// Add your custom methods and functionality below.
