// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tNoticeInfoDao is the data access object for the table t_notice_info.
// You can define custom methods on it to extend its functionality as needed.
type tNoticeInfoDao struct {
	*internal.TNoticeInfoDao
}

var (
	// TNoticeInfo is a globally accessible object for table t_notice_info operations.
	TNoticeInfo = tNoticeInfoDao{internal.NewTNoticeInfoDao()}
)

// Add your custom methods and functionality below.
