// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tRoleMenuDao is the data access object for the table t_role_menu.
// You can define custom methods on it to extend its functionality as needed.
type tRoleMenuDao struct {
	*internal.TRoleMenuDao
}

var (
	// TRoleMenu is a globally accessible object for table t_role_menu operations.
	TRoleMenu = tRoleMenuDao{internal.NewTRoleMenuDao()}
)

// Add your custom methods and functionality below.
