// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"github.com/yclw/mspay/internal/dao/internal"
)

// tSysConfigDao is the data access object for the table t_sys_config.
// You can define custom methods on it to extend its functionality as needed.
type tSysConfigDao struct {
	*internal.TSysConfigDao
}

var (
	// TSysConfig is a globally accessible object for table t_sys_config operations.
	TSysConfig = tSysConfigDao{internal.NewTSysConfigDao()}
)

// Add your custom methods and functionality below.
